test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google_dev:
  service: GCS
  project: sundance-glazing
  credentials: <%= Rails.root.join("config/secrets/gcs-credentials.json") %>
  bucket: portal-test_surchx

google_qa:
  service: GCS
  project: sundance-glazing
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'] %>
  bucket: portal-test_surchx

google_prod:
  service: GCS
  project: sundance-glazing
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'] %>
  bucket: portal-prod_surchx